export const atoi = new Map([
  ["a", 1],
  ["b", 2],
  ["c", 3],
  ["d", 4],
  ["e", 5],
  ["f", 6],
  ["g", 7],
  ["h", 8],
  ["i", 9],
  ["j", 10],
  ["k", 11],
  ["l", 12],
  ["m", 13],
  ["n", 14],
  ["o", 15],
  ["p", 16],
  ["q", 17],
  ["r", 18],
  ["s", 19],
  ["t", 20],
  ["u", 21],
  ["v", 22],
  ["w", 23],
  ["x", 24],
  ["y", 25],
  ["z", 26],
]);

export const atoi_inverse = new Map(Array.from(atoi).map(([a, i]) => [i, a]));

export const nato = new Map([
  [1, "alpha"],
  [2, "bravo"],
  [3, "charlie"],
  [4, "delta"],
  [5, "echo"],
  [6, "foxtrot"],
  [7, "golf"],
  [8, "hotel"],
  [9, "india"],
  [10, "juliett"],
  [11, "kilo"],
  [12, "lima"],
  [13, "mike"],
  [14, "november"],
  [15, "oscar"],
  [16, "papa"],
  [17, "quebec"],
  [18, "romeo"],
  [19, "sierra"],
  [20, "tango"],
  [21, "uniform"],
  [22, "victor"],
  [23, "whiskey"],
  [24, "xray"],
  [25, "yankee"],
  [26, "zulu"],

  ["a", "alpha"],
  ["b", "bravo"],
  ["c", "charlie"],
  ["d", "delta"],
  ["e", "echo"],
  ["f", "foxtrot"],
  ["g", "golf"],
  ["h", "hotel"],
  ["i", "india"],
  ["j", "juliett"],
  ["k", "kilo"],
  ["l", "lima"],
  ["m", "mike"],
  ["n", "november"],
  ["o", "oscar"],
  ["p", "papa"],
  ["q", "quebec"],
  ["r", "romeo"],
  ["s", "sierra"],
  ["t", "tango"],
  ["u", "uniform"],
  ["v", "victor"],
  ["w", "whiskey"],
  ["x", "xray"],
  ["y", "yankee"],
  ["z", "zulu"],
]);
